[book]
authors = ["Simone Colaci"]
language = "en"
multilingual = false
src = "src"
title = "AWS Developer Certification Notes"

[build]
build-dir = "docs"

[output.html]
additional-css = ["css/styles.css"]
additional-js = ["js/aws-icon.js"]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/Spronghi/aws-dev-cert-book"
edit-url-template = "https://github.com/Spronghi/aws-dev-cert-book/edit/main/{path}"

